# +---------------------------------------------+
# |      âœ¨ğŸš€ Starship configuration âœ¨ğŸš€       |
# +---------------------------------------------+
"$schema"         = 'https://starship.rs/config-schema.json'
palette           = "catppuccin_macchiato"

# +---------------------------------------------+
# |                   Prompt                    |
# +---------------------------------------------+
[character]
disabled          = false
success_symbol    = "[[ğŸ¦„](green) â¯](peach)"
error_symbol      = "[[ğŸ’©](red) â¯](peach)"

[directory]
disabled          = false
format            = "[$path]($style)[$read_only]($read_only_style) "
read_only         = " ğŸ”’"
style             = "bold lavender"
truncation_length = 4
truncate_to_repo  = true

[sudo]
disabled          = true
format            = "[$symbol]($style)"
style             = "bold red"
symbol            = "ğŸ§™ "

# +---------------------------------------------+
# |                     Git                     |
# +---------------------------------------------+
[git_branch]
disabled          = false
style             = "bold mauve"

# +---------------------------------------------+
# |                     Nix                     |
# +---------------------------------------------+
[nix_shell]
disabled          = false
format            = "[$symbol $name]($style) "
symbol            = "â„ï¸ "
style             = "bold blue"

# +---------------------------------------------+
# |                   Themes                    |
# +---------------------------------------------+
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
